//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindEducators.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FindEducatorsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FindEducatorsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindEducators.Resources.FindEducatorsResources", typeof(FindEducatorsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/banner-img-1.png.
        /// </summary>
        internal static string IMG_BANNER_IMAGE_1 {
            get {
                return ResourceManager.GetString("IMG_BANNER_IMAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-1.png.
        /// </summary>
        internal static string IMG_DUMMY_1 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-2.png.
        /// </summary>
        internal static string IMG_DUMMY_2 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-3.png.
        /// </summary>
        internal static string IMG_DUMMY_3 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-4.png.
        /// </summary>
        internal static string IMG_DUMMY_4 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-5.png.
        /// </summary>
        internal static string IMG_DUMMY_5 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-6.png.
        /// </summary>
        internal static string IMG_DUMMY_6 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-7.png.
        /// </summary>
        internal static string IMG_DUMMY_7 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/categories-icon-8.png.
        /// </summary>
        internal static string IMG_DUMMY_8 {
            get {
                return ResourceManager.GetString("IMG_DUMMY_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/logo.png.
        /// </summary>
        internal static string IMG_LOGO {
            get {
                return ResourceManager.GetString("IMG_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/menu-icon.png.
        /// </summary>
        internal static string IMG_MENU_ICON {
            get {
                return ResourceManager.GetString("IMG_MENU_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/option-icon.png.
        /// </summary>
        internal static string IMG_OPTION_ICON {
            get {
                return ResourceManager.GetString("IMG_OPTION_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/sidebar-logo.png.
        /// </summary>
        internal static string IMG_SIDEBAR_LOGO {
            get {
                return ResourceManager.GetString("IMG_SIDEBAR_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/signup.png.
        /// </summary>
        internal static string IMG_SIGN_UP {
            get {
                return ResourceManager.GetString("IMG_SIGN_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../content/template/images/user-img.png.
        /// </summary>
        internal static string IMG_USER_IMAGE_DUMMY {
            get {
                return ResourceManager.GetString("IMG_USER_IMAGE_DUMMY", resourceCulture);
            }
        }
    }
}
